// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskMode } from "./AskMode";
import type { AskQuestion } from "./AskQuestion";
import type { AskResolution } from "./AskResolution";
import type { DocInfo } from "./DocInfo";
import type { PermissionRisk } from "./PermissionRisk";
import type { RoundBlock } from "./RoundBlock";
import type { RoundDeltaKind } from "./RoundDeltaKind";
import type { SkillInfo } from "./SkillInfo";
import type { SkillRuntimeInfo } from "./SkillRuntimeInfo";
import type { TaskInfo } from "./TaskInfo";
import type { ToolCallDef } from "./ToolCallDef";
import type { ToolResultDef } from "./ToolResultDef";
import type { TurnData } from "./TurnData";
import type { UsageInfo } from "./UsageInfo";

export type Agent2Ui = { "type": "turn_start", turn_id: string, user_text: string, } | { "type": "turn_end", turn_id: string, stop_reason?: string, usage?: UsageInfo, } | { "type": "round_delta", turn_id: string, round_num: number, kind: RoundDeltaKind, delta: string, } | { "type": "round_complete", turn_id: string, round_num: number, thinking?: string, answer?: string, tool_calls?: Array<ToolCallDef>,
/**
 * Ordered blocks matching LLM output sequence (preferred).
 */
blocks?: Array<RoundBlock>,
/**
 * true = this is the final round of the turn
 */
is_final: boolean, } | { "type": "tool_results", turn_id: string, round_num: number, results: Array<ToolResultDef>, } | { "type": "tool_exec_delta", tool_call_id: string, delta: string, } | { "type": "session_restored", seed: string, turns: Array<TurnData>, tokens_used: number, cache_hit_pct: number,
/**
 * Total number of turns in this session.
 */
total_turns: number,
/**
 * True if there are more (older) turns beyond what's sent.
 */
has_more: boolean, } | { "type": "more_turns", turns: Array<TurnData>,
/**
 * True if there are still more (older) turns available.
 */
has_more: boolean, } | { "type": "session_created", seed: string, } | { "type": "error", message: string, } | { "type": "tool_notice", message: string,
/**
 * "warn" or "error"
 */
level: string, } | { "type": "plan_submitted",
/**
 * The plan_submit tool-call ID (must match PlanReview.call_id).
 */
call_id: string,
/**
 * PLAN.md content to display.
 */
plan_content: string, } | { "type": "plan_resolved",
/**
 * The plan_submit tool-call ID.
 */
call_id: string, approved: boolean, } | { "type": "dashboard", hp_connected: boolean, session_seed: string, tool_calls_total: number, tool_failures: number, current_phase: string, streaming: boolean, dsml_compat_count: number, documents?: Array<DocInfo>, recent_edits?: Array<string>, tasks?: Array<TaskInfo>, session_title?: string, usage?: UsageInfo, context_limit: number, model?: string, } | { "type": "done" } | { "type": "compact_start", turns_total: number, turns_keeping: number, } | { "type": "compact_end", summary_chars: number, turns_compacted: number, } | { "type": "compact_delta", delta: string, } | { "type": "cancelled" } | { "type": "shutdown_ack" } | { "type": "ready" } | { "type": "audit_record", tool_name: string, result_summary: string, success: boolean,
/**
 * ISO-8601 timestamp of the tool invocation.
 */
time: string,
/**
 * JSON-serialized tool arguments for formatting.
 */
args: string, } | { "type": "exec_progress", tool_call_id: string, stream: string, seq: bigint, chunk: string, } | { "type": "tool_call_preview", turn_id: string, round_num: number, index: number, id: string, name: string, args_so_far: string, } | { "type": "code_delta", lines_added: number, lines_removed: number, files_created: number, files_deleted: number, file?: string, } | { "type": "pong" } | { "type": "skills_changed",
/**
 * All discoverable skills in the workspace.
 */
available: Array<SkillInfo>,
/**
 * Names of currently loaded (explicit, $mention-activated) skills.
 */
active: Array<string>, catalog_revision: string, context_epoch: bigint, operation_revision: bigint, token_budget: number, token_usage: number, runtime: Array<SkillRuntimeInfo>, diagnostics: Array<string>, } | { "type": "skill_operation_resolved", operation_id: string, success: boolean, revision: bigint, error?: string, } | { "type": "permission_request", tool_call_id: string, tool_name: string,
/**
 * Human-readable reason for the request.
 */
reason: string,
/**
 * Target paths affected by the tool.
 */
paths: Array<string>,
/**
 * Tool category: "read", "write", "exec", "net".
 */
category: string,
/**
 * Current permission level (1-4).
 */
level: number,
/**
 * Intrinsic action impact, computed by the backend.
 */
risk: PermissionRisk,
/**
 * Plain-language effect of approving the action.
 */
consequence: string, } | { "type": "ask_user",
/**
 * Turn containing the original ask_user tool call.
 */
turn_id: string,
/**
 * Assistant round containing the original ask_user tool call.
 */
round_num: number,
/**
 * Original ask_user tool-call ID.
 */
ask_id: string,
/**
 * How to present the questions.
 */
mode: AskMode,
/**
 * One question per entry. Single mode typically has 1; Batch has N.
 */
questions: Array<AskQuestion>, } | { "type": "ask_resolved", ask_id: string, resolution: AskResolution, } | { "type": "ask_rejected", ask_id: string, message: string, };
