// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One answer in a user response.
 */
export type AskAnswer = {
/**
 * Matches AskQuestion.id.
 */
question_id: string,
/**
 * Selected option text, or custom input.
 */
answer: string, };
