// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display mode for an ask_user prompt.
 */
export type AskMode = "single" | "batch";
