// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One question in an ask_user prompt.
 */
export type AskQuestion = {
/**
 * Unique ID within this ask (e.g. "q1", "q2").
 */
id: string,
/**
 * Question text (supports Markdown).
 */
question: string,
/**
 * Preset choices. Empty = free-text only.
 */
options?: Array<string>,
/**
 * Allow the user to type a custom answer instead of picking an option.
 */
allow_custom: boolean, };
