// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an ask_user prompt left the active queue.
 */
export type AskResolution = "answered" | "dismissed";
