// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single code delta record for persistence.
 */
export type CodeDeltaRecord = { timestamp: bigint, lines_added: number, lines_removed: number, files_created: number, files_deleted: number, file?: string, };
