// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daily aggregated code stats.
 */
export type CodeDaily = { date: string, lines_added: number, lines_removed: number, files_created: number, files_deleted: number, };
