// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Document tracking entry.
 */
export type DocInfo = { tag: string, path: string, turns_since_read: number, is_stale: boolean, };
