// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File metadata snapshot for rich rendering.
 */
export type FileSnapshotInfo = { path: string, lines: number, size_bytes: bigint, start_line?: number, end_line?: number, tag?: string, };
