// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend-owned intrinsic impact of a permission-gated action.
 */
export type PermissionRisk = "low" | "medium" | "high";
