// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallDef } from "./ToolCallDef";

/**
 * One block in a round, preserving the LLM's output order.
 */
export type RoundBlock = { "type": "reasoning", content: string, } | { "type": "text", content: string, } | { "type": "tool", card: ToolCallDef, };
