// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Streaming block kind for RoundDelta.
 */
export type RoundDeltaKind = "thinking" | "tool_calling" | "answering";
