// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authoritative runtime state for one desktop session.
 */
export type SessionActivityState = "starting" | "idle" | "working" | "waiting_user" | "disconnected";
