// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSessionStateV2 } from "./SkillSessionStateV2";

/**
 * Session metadata — unified persistence + runtime state.
 *
 * Runtime-only fields are populated by the desktop session list.
 */
export type SessionMeta = { seed: string, created_at: bigint, updated_at: bigint, model: string, effort?: string, message_count: number, 
/**
 * Number of conversation turns (one user query + its assistant/tool chain).
 */
turn_count: number, last_summary: string, 
/**
 * Number of earliest turns compacted (skipped in LLM context).
 */
compact_skip: number, 
/**
 * Agent operating mode: 0=Normal, 1=Plan, 2=Code.
 * Persisted so PLAN/CODE mode survives agent restart within the same session.
 */
mode: number, skills: SkillSessionStateV2,
/** True if this session has messages in the Turso SQLite store. */
turso_backed: boolean,
/** True if an agent process is currently running for this session. */
running: boolean,
};
