// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionActivityState } from "./SessionActivityState";

/**
 * Snapshot/event payload emitted by the desktop bridge for every session.
 */
export type SessionActivity = { seed: string, state: SessionActivityState, turn_id?: string, seq: number, updated_at: number, };
