// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSessionEntry } from "./SkillSessionEntry";

export type SkillSessionStateV2 = { version: number, context_epoch: bigint, operation_revision: bigint, entries: Array<SkillSessionEntry>, };
