// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSessionEntryState } from "./SkillSessionEntryState";

export type SkillSessionEntry = { name: string, activation_order: bigint, source: string, state: SkillSessionEntryState, lease_remaining: number, };
