// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillInfo } from "./SkillInfo";
import type { SkillRuntimeInfo } from "./SkillRuntimeInfo";

/**
 * Payload for Agent2Ui::SkillsChanged.
 */
export type SkillsStatus = { 
/**
 * All discoverable skills in the workspace.
 */
available: Array<SkillInfo>, 
/**
 * Names of currently loaded (explicit, $mention-activated) skills.
 */
active: Array<string>, catalog_revision: string, context_epoch: bigint, operation_revision: bigint, token_budget: number, token_usage: number, runtime: Array<SkillRuntimeInfo>, diagnostics: Array<string>, };
