// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about an available skill for the frontend skills panel.
 */
export type SkillInfo = { name: string, description: string, 
/**
 * "project" or "user"
 */
scope: string, 
/**
 * Display path relative to workspace (e.g. "skills/deepx/deepx-debug")
 */
source: string, };
