// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillRuntimeInfo = { name: string, description: string,
/**
 * catalog, requested, active, review_due, or unavailable
 */
state: string, source: string, lease_remaining?: number, token_count: number, error?: string, };
