// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskInfo = { id: string, subject: string, description: string, status: string, };
