// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool call definition sent in RoundComplete.tool_calls.
 */
export type ToolCallDef = { id: string, name: string, 
/**
 * Human-readable args summary (e.g. "foo.rs", "search pattern")
 */
args_display: string, 
/**
 * Raw JSON arguments string
 */
args_json: string, };
