// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSnapshotInfo } from "./FileSnapshotInfo";

/**
 * Tool execution result sent in ToolResults.
 */
export type ToolResultDef = { tool_call_id: string, output: string, success: boolean, file?: FileSnapshotInfo, };
