// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskAnswer } from "./AskAnswer";

export type Ui2Agent = { "type": "user_input", text: string, } | { "type": "tool_call", id: string, name: string, action: string, args: any, } | { "type": "create_session" } | { "type": "cancel" } | { "type": "shutdown" } | { "type": "reload_config" } | { "type": "undo_turn", turn_id: string, } | { "type": "compact" } | { "type": "resume_session", seed: string, } | { "type": "new_session" } | { "type": "load_more_turns",
/**
 * Load turns older than this turn_id.
 */
before_turn_id: string,
/**
 * How many turns to load.
 */
count: number, } | { "type": "set_mode", mode: string, } | { "type": "permission_response", tool_call_id: string, approved: boolean,
/**
 * If true, trust the target folder permanently.
 */
trust_folder: boolean, } | { "type": "ask_response",
/**
 * Matches the ask_id from Agent2Ui::AskUser.
 */
ask_id: string, answers: Array<AskAnswer>, } | { "type": "ask_dismiss", ask_id: string, } | { "type": "plan_review",
/**
 * Matches the call_id of the plan_submit tool call.
 */
call_id: string, approved: boolean,
/**
 * Optional rejection reason.
 */
message: string, } | { "type": "unload_skill",
/**
 * Skill name (must match the name field in SKILL.md frontmatter).
 */
name: string, } | { "type": "activate_skill",
/**
 * Skill name (must match the name field in SKILL.md frontmatter).
 */
name: string, } | { "type": "skill_operation", operation_id: string, action: string, name: string, expected_revision: bigint, } | { "type": "reload_skills" };
