// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageInfo = { prompt_tokens: number, completion_tokens: number, total_tokens: number, prompt_cache_hit_tokens: number, prompt_cache_miss_tokens: number, reasoning_tokens: number, };
